-- MySQL Script generated by MySQL Workbench
-- Tue Aug 27 15:36:48 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema user_management
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema user_management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `user_management` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `user_management` ;

-- -----------------------------------------------------
-- Table `user_management`.`auth_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_management`.`auth_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `user_management`.`usermanagement_app_platform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_management`.`usermanagement_app_platform` (
  `id` CHAR(32) NOT NULL,
  `code` VARCHAR(54) NULL DEFAULT NULL,
  `name` VARCHAR(256) NOT NULL,
  `slug` VARCHAR(50) NULL DEFAULT NULL,
  `logo` VARCHAR(100) NULL DEFAULT NULL,
  `website` VARCHAR(256) NULL DEFAULT NULL,
  `domain_url` VARCHAR(200) NULL DEFAULT NULL,
  `domains_mapped` JSON NULL DEFAULT NULL,
  `status` SMALLINT UNSIGNED NOT NULL,
  `is_super_platform` TINYINT(1) NOT NULL,
  `created_by` VARCHAR(256) NULL DEFAULT NULL,
  `updated_by` VARCHAR(256) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  `parent_id_id` CHAR(32) NULL DEFAULT NULL,
  `host_url` VARCHAR(256) NULL DEFAULT NULL,
  `crud_callback_url` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `usermanagement_app_p_parent_id_id_17a993cd_fk_usermanag` (`parent_id_id` ASC) VISIBLE,
  INDEX `usermanagement_app_platform_slug_1e4f3226` (`slug` ASC) VISIBLE,
  CONSTRAINT `usermanagement_app_p_parent_id_id_17a993cd_fk_usermanag`
    FOREIGN KEY (`parent_id_id`)
    REFERENCES `user_management`.`usermanagement_app_platform` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `user_management`.`usermanagement_app_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_management`.`usermanagement_app_project` (
  `id` CHAR(32) NOT NULL,
  `name` VARCHAR(256) NOT NULL,
  `logo` VARCHAR(100) NULL DEFAULT NULL,
  `code` VARCHAR(256) NULL DEFAULT NULL,
  `website` VARCHAR(256) NULL DEFAULT NULL,
  `domain_url` VARCHAR(200) NULL DEFAULT NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  `created_by` VARCHAR(256) NULL DEFAULT NULL,
  `updated_by` VARCHAR(256) NULL DEFAULT NULL,
  `status` INT UNSIGNED NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  `parent_id_id` CHAR(32) NULL DEFAULT NULL,
  `platform_id_id` CHAR(32) NULL DEFAULT NULL,
  `domains_mapped` JSON NULL DEFAULT NULL,
  `host_url` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `usermanagement_app_p_parent_id_id_d82487f8_fk_usermanag` (`parent_id_id` ASC) VISIBLE,
  INDEX `usermanagement_app_p_platform_id_id_5cb01070_fk_usermanag` (`platform_id_id` ASC) VISIBLE,
  CONSTRAINT `usermanagement_app_p_parent_id_id_d82487f8_fk_usermanag`
    FOREIGN KEY (`parent_id_id`)
    REFERENCES `user_management`.`usermanagement_app_project` (`id`),
  CONSTRAINT `usermanagement_app_p_platform_id_id_5cb01070_fk_usermanag`
    FOREIGN KEY (`platform_id_id`)
    REFERENCES `user_management`.`usermanagement_app_platform` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `user_management`.`usermanagement_app_fcmkeys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_management`.`usermanagement_app_fcmkeys` (
  `id` CHAR(32) NOT NULL,
  `api_key` LONGTEXT NULL DEFAULT NULL,
  `credentials_json` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  `platform_id_id` CHAR(32) NULL DEFAULT NULL,
  `project_id_id` CHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `usermanagem_platfor_e9f148_idx` (`platform_id_id` ASC) VISIBLE,
  INDEX `usermanagem_project_bcd952_idx` (`project_id_id` ASC) VISIBLE,
  CONSTRAINT `usermanagement_app_f_platform_id_id_ce02203b_fk_usermanag`
    FOREIGN KEY (`platform_id_id`)
    REFERENCES `user_management`.`usermanagement_app_platform` (`id`),
  CONSTRAINT `usermanagement_app_f_project_id_id_7c8b57c8_fk_usermanag`
    FOREIGN KEY (`project_id_id`)
    REFERENCES `user_management`.`usermanagement_app_project` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `user_management`.`usermanagement_app_mappedurls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_management`.`usermanagement_app_mappedurls` (
  `id` CHAR(32) NOT NULL,
  `domain_url` VARCHAR(200) NULL DEFAULT NULL,
  `status` INT UNSIGNED NOT NULL,
  `created_by` VARCHAR(256) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  `platform_id_id` CHAR(32) NULL DEFAULT NULL,
  `project_id_id` CHAR(32) NULL DEFAULT NULL,
  `platform_login` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usermanagement_app_m_platform_id_id_fb25b4c0_fk_usermanag` (`platform_id_id` ASC) VISIBLE,
  INDEX `usermanagement_app_m_project_id_id_121ba2ca_fk_usermanag` (`project_id_id` ASC) VISIBLE,
  CONSTRAINT `usermanagement_app_m_platform_id_id_fb25b4c0_fk_usermanag`
    FOREIGN KEY (`platform_id_id`)
    REFERENCES `user_management`.`usermanagement_app_platform` (`id`),
  CONSTRAINT `usermanagement_app_m_project_id_id_121ba2ca_fk_usermanag`
    FOREIGN KEY (`project_id_id`)
    REFERENCES `user_management`.`usermanagement_app_project` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `user_management`.`usermanagement_app_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_management`.`usermanagement_app_member` (
  `password` VARCHAR(128) NOT NULL,
  `id` CHAR(32) NOT NULL,
  `email_id` VARCHAR(254) NULL DEFAULT NULL,
  `phone_number` VARCHAR(88) NULL DEFAULT NULL,
  `is_superuser` TINYINT(1) NOT NULL,
  `last_login` DATETIME(6) NULL DEFAULT NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  `status` INT UNSIGNED NOT NULL,
  `created_by` VARCHAR(256) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  `first_name` VARCHAR(256) NULL DEFAULT NULL,
  `last_name` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_id` (`email_id` ASC) VISIBLE,
  UNIQUE INDEX `phone_number` (`phone_number` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `user_management`.`usermanagement_app_memberinformation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_management`.`usermanagement_app_memberinformation` (
  `id` CHAR(32) NOT NULL,
  `first_name` VARCHAR(256) NULL DEFAULT NULL,
  `last_name` VARCHAR(256) NULL DEFAULT NULL,
  `email_id` VARCHAR(254) NULL DEFAULT NULL,
  `phone_number` VARCHAR(88) NULL DEFAULT NULL,
  `country_code` VARCHAR(10) NULL DEFAULT NULL,
  `password` VARCHAR(256) NULL DEFAULT NULL,
  `address_line_1` LONGTEXT NULL DEFAULT NULL,
  `address_line_2` LONGTEXT NULL DEFAULT NULL,
  `country` VARCHAR(256) NULL DEFAULT NULL,
  `state` VARCHAR(256) NULL DEFAULT NULL,
  `city` VARCHAR(256) NULL DEFAULT NULL,
  `zip_code` VARCHAR(256) NULL DEFAULT NULL,
  `profile_image` VARCHAR(100) NULL DEFAULT NULL,
  `status` INT UNSIGNED NOT NULL,
  `created_by` VARCHAR(256) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usermanagem_first_n_b67d97_idx` (`first_name` ASC, `last_name` ASC) VISIBLE,
  INDEX `usermanagem_first_n_e3beb6_idx` (`first_name` ASC) VISIBLE,
  INDEX `usermanagem_last_na_4a9c93_idx` (`last_name` ASC) VISIBLE,
  INDEX `usermanagem_email_i_c3609d_idx` (`email_id` ASC) VISIBLE,
  INDEX `usermanagem_phone_n_f9c984_idx` (`phone_number` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `user_management`.`usermanagement_app_memberloginactivity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_management`.`usermanagement_app_memberloginactivity` (
  `id` CHAR(32) NOT NULL,
  `logged_in_at` DATETIME(6) NOT NULL,
  `device_type` VARCHAR(64) NULL DEFAULT NULL,
  `ip_address` CHAR(39) NULL DEFAULT NULL,
  `member_id_id` CHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `usermanagement_app_m_member_id_id_40f05537_fk_usermanag` (`member_id_id` ASC) VISIBLE,
  CONSTRAINT `usermanagement_app_m_member_id_id_40f05537_fk_usermanag`
    FOREIGN KEY (`member_id_id`)
    REFERENCES `user_management`.`usermanagement_app_member` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `user_management`.`usermanagement_app_memberotp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_management`.`usermanagement_app_memberotp` (
  `id` CHAR(32) NOT NULL,
  `otp` VARCHAR(6) NOT NULL,
  `is_validated` TINYINT(1) NOT NULL,
  `platform_id` CHAR(32) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `expired_at` DATETIME(6) NOT NULL,
  `member_id_id` CHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `usermanagement_app_m_member_id_id_967930f8_fk_usermanag` (`member_id_id` ASC) VISIBLE,
  CONSTRAINT `usermanagement_app_m_member_id_id_967930f8_fk_usermanag`
    FOREIGN KEY (`member_id_id`)
    REFERENCES `user_management`.`usermanagement_app_member` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `user_management`.`usermanagement_app_memberpassworduniqueidentifier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_management`.`usermanagement_app_memberpassworduniqueidentifier` (
  `id` CHAR(32) NOT NULL,
  `password_redirect_url` VARCHAR(256) NULL DEFAULT NULL,
  `expired` INT UNSIGNED NOT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `member_id_id` CHAR(32) NULL DEFAULT NULL,
  `domain_url` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `usermanagement_app_m_member_id_id_238dd48c_fk_usermanag` (`member_id_id` ASC) VISIBLE,
  CONSTRAINT `usermanagement_app_m_member_id_id_238dd48c_fk_usermanag`
    FOREIGN KEY (`member_id_id`)
    REFERENCES `user_management`.`usermanagement_app_member` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `user_management`.`usermanagement_app_usertype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_management`.`usermanagement_app_usertype` (
  `id` CHAR(32) NOT NULL,
  `name` VARCHAR(256) NOT NULL,
  `fields` JSON NULL DEFAULT NULL,
  `created_by` VARCHAR(256) NULL DEFAULT NULL,
  `updated_by` VARCHAR(256) NULL DEFAULT NULL,
  `status` INT UNSIGNED NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  `platform_id_id` CHAR(32) NULL DEFAULT NULL,
  `project_id_id` CHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `usermanagement_app_u_platform_id_id_e9af029e_fk_usermanag` (`platform_id_id` ASC) VISIBLE,
  INDEX `usermanagement_app_u_project_id_id_543a53d7_fk_usermanag` (`project_id_id` ASC) VISIBLE,
  CONSTRAINT `usermanagement_app_u_platform_id_id_e9af029e_fk_usermanag`
    FOREIGN KEY (`platform_id_id`)
    REFERENCES `user_management`.`usermanagement_app_platform` (`id`),
  CONSTRAINT `usermanagement_app_u_project_id_id_543a53d7_fk_usermanag`
    FOREIGN KEY (`project_id_id`)
    REFERENCES `user_management`.`usermanagement_app_project` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `user_management`.`usermanagement_app_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_management`.`usermanagement_app_roles` (
  `id` CHAR(32) NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  `created_by` VARCHAR(256) NULL DEFAULT NULL,
  `updated_by` VARCHAR(256) NULL DEFAULT NULL,
  `status` INT UNSIGNED NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  `platform_id_id` CHAR(32) NULL DEFAULT NULL,
  `project_id_id` CHAR(32) NULL DEFAULT NULL,
  `usertype_id_id` CHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `usermanagement_app_r_platform_id_id_5bd871b0_fk_usermanag` (`platform_id_id` ASC) VISIBLE,
  INDEX `usermanagement_app_r_project_id_id_a9eb6021_fk_usermanag` (`project_id_id` ASC) VISIBLE,
  INDEX `usermanagement_app_r_usertype_id_id_06efcc02_fk_usermanag` (`usertype_id_id` ASC) VISIBLE,
  CONSTRAINT `usermanagement_app_r_platform_id_id_5bd871b0_fk_usermanag`
    FOREIGN KEY (`platform_id_id`)
    REFERENCES `user_management`.`usermanagement_app_platform` (`id`),
  CONSTRAINT `usermanagement_app_r_project_id_id_a9eb6021_fk_usermanag`
    FOREIGN KEY (`project_id_id`)
    REFERENCES `user_management`.`usermanagement_app_project` (`id`),
  CONSTRAINT `usermanagement_app_r_usertype_id_id_06efcc02_fk_usermanag`
    FOREIGN KEY (`usertype_id_id`)
    REFERENCES `user_management`.`usermanagement_app_usertype` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `user_management`.`usermanagement_app_memberplatform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_management`.`usermanagement_app_memberplatform` (
  `id` CHAR(32) NOT NULL,
  `domain_url` VARCHAR(200) NULL DEFAULT NULL,
  `status` INT UNSIGNED NOT NULL,
  `created_by` VARCHAR(256) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  `member_id_id` CHAR(32) NULL DEFAULT NULL,
  `memberinformation_id_id` CHAR(32) NULL DEFAULT NULL,
  `platform_id_id` CHAR(32) NULL DEFAULT NULL,
  `project_id_id` CHAR(32) NULL DEFAULT NULL,
  `roles_id_id` CHAR(32) NULL DEFAULT NULL,
  `usertype_id_id` CHAR(32) NULL DEFAULT NULL,
  `apple_token` LONGTEXT NULL DEFAULT NULL,
  `device_id` LONGTEXT NULL DEFAULT NULL,
  `hide_user` TINYINT(1) NULL DEFAULT NULL,
  `is_password_updated` TINYINT(1) NULL DEFAULT NULL,
  `is_super_admin` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `usermanagement_app_m_platform_id_id_6cd1ed9f_fk_usermanag` (`platform_id_id` ASC) VISIBLE,
  INDEX `usermanagement_app_m_project_id_id_7c0e2175_fk_usermanag` (`project_id_id` ASC) VISIBLE,
  INDEX `usermanagement_app_m_roles_id_id_c8dbcb39_fk_usermanag` (`roles_id_id` ASC) VISIBLE,
  INDEX `usermanagement_app_m_usertype_id_id_5532e39d_fk_usermanag` (`usertype_id_id` ASC) VISIBLE,
  INDEX `usermanagement_app_m_member_id_id_0ab775ab_fk_usermanag` (`member_id_id` ASC) VISIBLE,
  INDEX `usermanagement_app_m_memberinformation_id_af294398_fk_usermanag` (`memberinformation_id_id` ASC) VISIBLE,
  CONSTRAINT `usermanagement_app_m_member_id_id_0ab775ab_fk_usermanag`
    FOREIGN KEY (`member_id_id`)
    REFERENCES `user_management`.`usermanagement_app_member` (`id`),
  CONSTRAINT `usermanagement_app_m_memberinformation_id_af294398_fk_usermanag`
    FOREIGN KEY (`memberinformation_id_id`)
    REFERENCES `user_management`.`usermanagement_app_memberinformation` (`id`),
  CONSTRAINT `usermanagement_app_m_platform_id_id_6cd1ed9f_fk_usermanag`
    FOREIGN KEY (`platform_id_id`)
    REFERENCES `user_management`.`usermanagement_app_platform` (`id`),
  CONSTRAINT `usermanagement_app_m_project_id_id_7c0e2175_fk_usermanag`
    FOREIGN KEY (`project_id_id`)
    REFERENCES `user_management`.`usermanagement_app_project` (`id`),
  CONSTRAINT `usermanagement_app_m_roles_id_id_c8dbcb39_fk_usermanag`
    FOREIGN KEY (`roles_id_id`)
    REFERENCES `user_management`.`usermanagement_app_roles` (`id`),
  CONSTRAINT `usermanagement_app_m_usertype_id_id_5532e39d_fk_usermanag`
    FOREIGN KEY (`usertype_id_id`)
    REFERENCES `user_management`.`usermanagement_app_usertype` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `user_management`.`usermanagement_app_rightname`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_management`.`usermanagement_app_rightname` (
  `id` CHAR(32) NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `created_by` VARCHAR(256) NULL DEFAULT NULL,
  `updated_by` VARCHAR(256) NULL DEFAULT NULL,
  `status` INT UNSIGNED NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  `platform_id_id` CHAR(32) NULL DEFAULT NULL,
  `project_id_id` CHAR(32) NULL DEFAULT NULL,
  `default_right_name` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usermanagement_app_r_platform_id_id_e4fc7e91_fk_usermanag` (`platform_id_id` ASC) VISIBLE,
  INDEX `usermanagement_app_r_project_id_id_9b470f0c_fk_usermanag` (`project_id_id` ASC) VISIBLE,
  CONSTRAINT `usermanagement_app_r_platform_id_id_e4fc7e91_fk_usermanag`
    FOREIGN KEY (`platform_id_id`)
    REFERENCES `user_management`.`usermanagement_app_platform` (`id`),
  CONSTRAINT `usermanagement_app_r_project_id_id_9b470f0c_fk_usermanag`
    FOREIGN KEY (`project_id_id`)
    REFERENCES `user_management`.`usermanagement_app_project` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `user_management`.`usermanagement_app_rights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_management`.`usermanagement_app_rights` (
  `id` CHAR(32) NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `created_by` VARCHAR(256) NULL DEFAULT NULL,
  `updated_by` VARCHAR(256) NULL DEFAULT NULL,
  `status` INT UNSIGNED NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  `platform_id_id` CHAR(32) NULL DEFAULT NULL,
  `project_id_id` CHAR(32) NULL DEFAULT NULL,
  `rightname_id_id` CHAR(32) NULL DEFAULT NULL,
  `default_right` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usermanagement_app_r_platform_id_id_c7feab46_fk_usermanag` (`platform_id_id` ASC) VISIBLE,
  INDEX `usermanagement_app_r_project_id_id_d87905c9_fk_usermanag` (`project_id_id` ASC) VISIBLE,
  INDEX `usermanagement_app_r_rightname_id_id_3db1fb53_fk_usermanag` (`rightname_id_id` ASC) VISIBLE,
  CONSTRAINT `usermanagement_app_r_platform_id_id_c7feab46_fk_usermanag`
    FOREIGN KEY (`platform_id_id`)
    REFERENCES `user_management`.`usermanagement_app_platform` (`id`),
  CONSTRAINT `usermanagement_app_r_project_id_id_d87905c9_fk_usermanag`
    FOREIGN KEY (`project_id_id`)
    REFERENCES `user_management`.`usermanagement_app_project` (`id`),
  CONSTRAINT `usermanagement_app_r_rightname_id_id_3db1fb53_fk_usermanag`
    FOREIGN KEY (`rightname_id_id`)
    REFERENCES `user_management`.`usermanagement_app_rightname` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `user_management`.`usermanagement_app_roles_rights_ids`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_management`.`usermanagement_app_roles_rights_ids` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `roles_id` CHAR(32) NOT NULL,
  `rights_id` CHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usermanagement_app_roles_roles_id_rights_id_89ee6a13_uniq` (`roles_id` ASC, `rights_id` ASC) VISIBLE,
  INDEX `usermanagement_app_r_rights_id_22819a4c_fk_usermanag` (`rights_id` ASC) VISIBLE,
  CONSTRAINT `usermanagement_app_r_rights_id_22819a4c_fk_usermanag`
    FOREIGN KEY (`rights_id`)
    REFERENCES `user_management`.`usermanagement_app_rights` (`id`),
  CONSTRAINT `usermanagement_app_r_roles_id_e11f4203_fk_usermanag`
    FOREIGN KEY (`roles_id`)
    REFERENCES `user_management`.`usermanagement_app_roles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 97
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
